# Generated by Django 3.1.2 on 2020-12-17 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0002_auto_20201217_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifyPasswordCaptcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha', models.CharField(max_length=6, verbose_name='验证码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('send_time', models.DateTimeField(default=datetime.datetime(2020, 12, 17, 19, 50, 30, 932877), verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '修改密码验证码',
                'verbose_name_plural': '修改密码验证码',
            },
        ),
        migrations.CreateModel(
            name='RegisterCaptcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha', models.CharField(max_length=6, verbose_name='验证码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('send_time', models.DateTimeField(default=datetime.datetime(2020, 12, 17, 19, 50, 30, 932515), verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '注册验证码',
                'verbose_name_plural': '注册验证码',
            },
        ),
        migrations.DeleteModel(
            name='EmailVerifyRecord',
        ),
    ]
