# Generated by Django 3.1.2 on 2020-12-17 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0003_auto_20201217_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordCaptcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha', models.CharField(max_length=6, verbose_name='验证码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('send_time', models.DateTimeField(default=datetime.datetime(2020, 12, 17, 19, 57, 2, 772270), verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '修改密码验证码',
                'verbose_name_plural': '修改密码验证码',
            },
        ),
        migrations.DeleteModel(
            name='ModifyPasswordCaptcha',
        ),
        migrations.AlterField(
            model_name='registercaptcha',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 19, 57, 2, 771896), verbose_name='发送时间'),
        ),
    ]
