# Generated by Django 3.1.2 on 2020-12-17 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0004_auto_20201217_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpasswordcaptcha',
            name='send_time',
        ),
        migrations.RemoveField(
            model_name='registercaptcha',
            name='send_time',
        ),
        migrations.AddField(
            model_name='forgotpasswordcaptcha',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 20, 34, 24), verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='registercaptcha',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 20, 34, 24), verbose_name='过期时间'),
        ),
    ]
